version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:860061945305:task-definition/ramkishore-process-pension:1"
        LoadBalancerInfo:
          ContainerName: "ecr-ramkishore-process-pension"
          ContainerPort: "8003"

        PlatformVersion: "LATEST"